
export type Language = 'en' | 'id';

export const translations = {
  en: {
    appName: "Pizza 'N Gooo Loyalty",
    loginTitle: "Staff Access",
    password: "Password",
    login: "Login",
    loginError: "Incorrect password.",
    dashboard: "Home",
    marketing: "Marketing",
    registerCustomer: "Register Customer",
    customersAndCards: "Customers & Cards",
    transactions: "Transactions",
    backupExport: "Backup / Export",
    fullName: "Full Name",
    operatorName: "Staff / Operator Name",
    instagramHandle: "Instagram Handle",
    phoneNumber: "Phone Number",
    cardType: "Card Type",
    vip: "VIP",
    fidelity: "Fidelity",
    register: "Register",
    customerRegistered: "Customer successfully registered!",
    searchCustomer: "Search by name or card ID...",
    noCustomers: "No customers found.",
    registeredOn: "Registered on",
    registeredByLabel: "By",
    viewCards: "View Cards",
    noCards: "This customer has no cards.",
    cardId: "Card ID",
    points: "Points",
    benefits: "Benefits",
    vipBenefit1: "15% discount on all purchases",
    vipBenefit2: "Buy 1 Get 1 Free on Wednesdays",
    fidelityReward: "Free Pizza Roma L Size",
    progress: "Progress",
    share: "Send on WhatsApp",
    shareMessage: "Here is your Pizza 'N Gooo loyalty card! (Please attach the image you just saved)",
    addTransaction: "Add Transaction",
    transactionAmount: "Transaction Amount (IDR)",
    scanReceipt: "Scan Receipt",
    processingReceipt: "Processing receipt...",
    receiptTotalFound: "Total found: ",
    receiptError: "Could not read receipt. Please enter amount manually.",
    submit: "Submit & Notify",
    transactionAdded: "Transaction added successfully!",
    transactionHistory: "Transaction History",
    noTransactions: "No transactions recorded yet.",
    date: "Date",
    amount: "Amount",
    pointsEarned: "Points Earned",
    customer: "Customer",
    manualBackup: "Manual Backup",
    exportAsJSON: "Export as JSON",
    exportAsCSV: "Export as CSV",
    importData: "Import Database (JSON)",
    importWarning: "Warning: This will overwrite all current data on this device. Continue?",
    importSuccess: "Database successfully imported!",
    importError: "Invalid file format.",
    dataExported: "Data exported successfully.",
    generatingCard: "Generating...",
    card: "Card",
    cardNotFound: "Card not found",
    scanQRCode: "Scan QR Code",
    searchByNameOrCardId: "Search by Name or Card ID...",
    stopScanning: "Stop Scanning",
    qrScanning: "Point camera at QR code...",
    noCameraPermission: "Could not get camera permissions.",
    actions: "Actions",
    editTransaction: "Edit Transaction",
    deleteTransaction: "Delete Transaction",
    confirmDeletion: "Confirm Deletion",
    areYouSureDelete: "Are you sure you want to delete this transaction? This action cannot be undone.",
    cancel: "Cancel",
    delete: "Delete",
    saveChanges: "Save Changes",
    transactionUpdated: "Transaction updated successfully!",
    transactionDeleted: "Transaction deleted successfully!",
    sharingNotSupportedDesktop: "Card image downloaded! Opening WhatsApp... Please attach the image manually.",
    deleteCard: "Delete Card",
    areYouSureDeleteCard: "Are you sure you want to delete this card? All associated transactions will also be permanently deleted. This action cannot be undone.",
    cardDeleted: "Card has been successfully deleted.",
    sharingFailed: "Sharing failed. Please try again.",
    help: "Help",
    operatorGuide: "Operator Guide",
    guideStep1Title: "1. Registration",
    guideStep1Desc: "Go to 'Register Customer'. Enter name, phone, and choose VIP (Discount) or Fidelity (Points).",
    guideStep2Title: "2. Share Card",
    guideStep2Desc: "In 'Customers & Cards', find the customer and click 'Share'. The card image will be generated.",
    guideStep3Title: "3. Transactions",
    guideStep3Desc: "Go to 'Transactions'. Scan the customer's QR code or search by name. Enter the amount paid.",
    guideStep4Title: "4. Points & Rewards",
    guideStep4Desc: "Fidelity points are added automatically. When they reach 75,000 IDR, they get 1 point. 10 points = Free Pizza.",
    settings: "Settings",
    syncUrl: "Google Sync URL",
    syncUrlPlaceholder: "Paste your Google Apps Script URL here...",
    saveSettings: "Save Settings",
    syncing: "Syncing...",
    synced: "Synced",
    syncError: "Sync Error",
    cloudSyncDescription: "Paste the URL from your Google Apps Script deployment to enable automatic synchronization between devices using your Google Drive.",
    syncNow: "Sync Now",
    dataSynced: "Data synchronized with cloud!",
    syncFailed: "Sync failed. Check URL.",
    shareApp: "Share App",
    linkCopied: "Link Copied! Paste on WhatsApp.",
    install: "Install App",
    openInBrowser: "Open in System Browser",
    shareAppDesc: "Scan this QR code to open the app on another device.",
    installApp: "Install App",
    installAppDesc: "Install for a better experience.",
    iosInstall: "Tap Share -> Add to Home Screen",
    howToInstall: "How to Install",
    installInstructions: "To install this app on your phone:",
    installAndroid: "Android: Click 'Install' or tap the menu (⋮) and select 'Add to Home Screen'.",
    installIOS: "iOS (iPhone): 1. Tap the Share button (box with arrow) at the bottom.\n2. Scroll down.\n3. Tap 'Add to Home Screen'.",
    whatsappImageSaved: "Image saved to Gallery! Opening WhatsApp... Please attach the image you just saved.",
    shareStep1: "1. Long press image to Save",
    shareStep2: "2. Open WhatsApp",
    readyToShare: "Card Ready!",
    close: "Close",
    dob: "Date of Birth",
    entryFee: "Entry Fee (30.000 IDR)",
    paid: "Paid",
    unpaid: "Not Paid",
    markAsPaid: "Mark Fee as Paid?",
    feeAlert: "FEE UNPAID",
    deleteCustomer: "Delete Customer",
    deleteCustomerConfirm: "Delete this customer? This will delete all their cards and transactions forever.",
    waVipMsg: "Thank you for your purchase at Pizza 'N Gooo! You saved money with your VIP Card today! 🍕🔥",
    waFidelityMsg: "Thank you for your purchase at Pizza 'N Gooo! You have collected",
    pointsMsg: "points. Keep going for your Free Pizza! 🍕🔥",
    selectStaff: "Select Staff",
    camera: "Camera",
    // New Translations
    upcomingBirthdays: "🎂 Upcoming Birthdays (7 Days)",
    topStaff: "🏆 Top Staff (Registrations)",
    weeklySales: "📉 Weekly Sales Overview",
    dormantCustomers: "💤 Dormant Customers (>30 Days)",
    sendWishes: "Send Wishes",
    missYouMsg: "We miss you at Pizza 'N Gooo! Come back for a special treat! 🍕",
    birthdayMsg: "Happy Birthday from Pizza 'N Gooo! 🎂 Come celebrate with us and get a special treat!",
    createVoucher: "Create Voucher",
    voucherTitle: "Voucher Title",
    voucherAmount: "Discount/Value",
    voucherDesc: "Description",
    generateVoucher: "Generate & Share",
    preview: "Preview",
    marketingTools: "Marketing Tools",
    noBirthdays: "No birthdays this week.",
    noDormant: "No dormant customers found.",
    totalSales: "Total Sales",
    last7Days: "Last 7 Days"
  },
  id: {
    appName: "Loyalitas Pizza 'N Gooo",
    loginTitle: "Akses Staf",
    password: "Kata Sandi",
    login: "Masuk",
    loginError: "Kata sandi salah.",
    dashboard: "Beranda",
    marketing: "Pemasaran",
    registerCustomer: "Daftarkan Pelanggan",
    customersAndCards: "Pelanggan & Kartu",
    transactions: "Transaksi",
    backupExport: "Cadangkan / Ekspor",
    fullName: "Nama Lengkap",
    operatorName: "Nama Staf / Operator",
    instagramHandle: "Akun Instagram",
    phoneNumber: "Nomor Telepon",
    cardType: "Jenis Kartu",
    vip: "VIP",
    fidelity: "Fidelity",
    register: "Daftarkan",
    customerRegistered: "Pelanggan berhasil didaftarkan!",
    searchCustomer: "Cari berdasarkan nama atau ID kartu...",
    noCustomers: "Tidak ada pelanggan ditemukan.",
    registeredOn: "Terdaftar pada",
    registeredByLabel: "Oleh",
    viewCards: "Lihat Kartu",
    noCards: "Pelanggan ini tidak memiliki kartu.",
    cardId: "ID Kartu",
    points: "Poin",
    benefits: "Keuntungan",
    vipBenefit1: "Diskon 15% untuk semua pembelian",
    vipBenefit2: "Beli 1 Gratis 1 setiap hari Rabu",
    fidelityReward: "Gratis Pizza Roma Ukuran L",
    progress: "Progres",
    share: "Kirim ke WhatsApp",
    shareMessage: "Ini kartu loyalitas Pizza 'N Gooo Anda! (Mohon lampirkan gambar yang baru disimpan)",
    addTransaction: "Tambah Transaksi",
    transactionAmount: "Jumlah Transaksi (IDR)",
    scanReceipt: "Foto Struk",
    processingReceipt: "Memproses struk...",
    receiptTotalFound: "Total ditemukan: ",
    receiptError: "Tidak dapat membaca struk. Masukkan jumlah manual.",
    submit: "Kirim & WA",
    transactionAdded: "Transaksi berhasil ditambahkan!",
    transactionHistory: "Riwayat Transaksi",
    noTransactions: "Belum ada transaksi yang tercatat.",
    date: "Tanggal",
    amount: "Jumlah",
    pointsEarned: "Poin Diperoleh",
    customer: "Pelanggan",
    manualBackup: "Pencadangan Manual",
    exportAsJSON: "Ekspor sebagai JSON",
    exportAsCSV: "Ekspor sebagai CSV",
    importData: "Impor Database (JSON)",
    importWarning: "Peringatan: Ini akan menimpa semua data saat ini di perangkat ini. Lanjutkan?",
    importSuccess: "Database berhasil diimpor!",
    importError: "Format file tidak valid.",
    dataExported: "Data berhasil diekspor.",
    generatingCard: "Membuat...",
    card: "Kartu",
    cardNotFound: "Kartu tidak ditemukan",
    scanQRCode: "Pindai Kode QR",
    searchByNameOrCardId: "Cari berdasarkan Nama atau ID Kartu...",
    stopScanning: "Hentikan Pemindaian",
    qrScanning: "Arahkan kamera ke kode QR...",
    noCameraPermission: "Tidak bisa mendapatkan izin kamera.",
    actions: "Aksi",
    editTransaction: "Ubah Transaksi",
    deleteTransaction: "Hapus Transaksi",
    confirmDeletion: "Konfirmasi Penghapusan",
    areYouSureDelete: "Apakah Anda yakin ingin menghapus transaksi ini? Tindakan ini tidak dapat dibatalkan.",
    cancel: "Batal",
    delete: "Hapus",
    saveChanges: "Simpan Perubahan",
    transactionUpdated: "Transaksi berhasil diperbarui!",
    transactionDeleted: "Transaksi berhasil dihapus!",
    sharingNotSupportedDesktop: "Gambar kartu diunduh! Membuka WhatsApp... Harap lampirkan gambar secara manual.",
    deleteCard: "Hapus Kartu",
    areYouSureDeleteCard: "Apakah Anda yakin ingin menghapus kartu ini? Semua transaksi terkait juga akan dihapus secara permanen. Tindakan ini tidak bisa dibatalkan.",
    cardDeleted: "Kartu telah berhasil dihapus.",
    sharingFailed: "Gagal berbagi. Silakan coba lagi.",
    help: "Bantuan",
    operatorGuide: "Panduan Operator",
    guideStep1Title: "1. Pendaftaran",
    guideStep1Desc: "Buka 'Daftarkan Pelanggan'. Masukkan nama, telepon, dan pilih VIP (Diskon) atau Fidelity (Poin).",
    guideStep2Title: "2. Bagikan Kartu",
    guideStep2Desc: "Di 'Pelanggan & Kartu', cari pelanggan dan klik 'Bagikan'. Gambar kartu akan dibuat.",
    guideStep3Title: "3. Transaksi",
    guideStep3Desc: "Buka 'Transaksi'. Pindai kode QR pelanggan atau cari nama. Masukkan jumlah pembayaran.",
    guideStep4Title: "4. Poin & Hadiah",
    guideStep4Desc: "Poin Fidelity ditambahkan otomatis. Tiap 75.000 IDR = 1 poin. 10 poin = Gratis Pizza.",
    settings: "Pengaturan",
    syncUrl: "URL Sinkronisasi Google",
    syncUrlPlaceholder: "Tempel URL Google Apps Script Anda di sini...",
    saveSettings: "Simpan Pengaturan",
    syncing: "Sinkronisasi...",
    synced: "Tersinkronisasi",
    syncError: "Kesalahan Sinkronisasi",
    cloudSyncDescription: "Tempel URL dari penerapan Google Apps Script Anda untuk mengaktifkan sinkronisasi otomatis antar perangkat menggunakan Google Drive Anda.",
    syncNow: "Sinkronkan Sekarang",
    dataSynced: "Data disinkronkan dengan cloud!",
    syncFailed: "Sinkronisasi gagal. Periksa URL.",
    shareApp: "Bagikan Aplikasi",
    linkCopied: "Link App Disalin! Tempel di WhatsApp.",
    install: "Instal Aplikasi",
    openInBrowser: "Buka di Browser",
    shareAppDesc: "Pindai kode QR ini untuk membuka aplikasi di perangkat lain.",
    installApp: "Instal Aplikasi",
    installAppDesc: "Instal untuk pengalaman lebih baik.",
    iosInstall: "Ketuk Bagikan -> Tambah ke Layar Utama",
    howToInstall: "Cara Menginstal",
    installInstructions: "Untuk menginstal aplikasi ini di ponsel Anda:",
    installAndroid: "Android: Klik 'Instal' atau ketuk menu (⋮) dan pilih 'Tambahkan ke Layar Utama'.",
    installIOS: "iOS (iPhone): 1. Ketuk tombol Bagikan (kotak dengan panah) di bawah.\n2. Gulir ke bawah.\n3. Ketuk 'Tambahkan ke Layar Utama'.",
    whatsappImageSaved: "Gambar tersimpan di Galeri! Membuka WhatsApp... Silakan lampirkan gambar yang baru saja disimpan.",
    shareStep1: "1. Tahan gambar utk Simpan",
    shareStep2: "2. Buka WhatsApp",
    readyToShare: "Kartu Siap!",
    close: "Tutup",
    dob: "Tanggal Lahir",
    entryFee: "Biaya Masuk (30.000 IDR)",
    paid: "Lunas",
    unpaid: "Belum Lunas",
    markAsPaid: "Tandai sudah bayar?",
    feeAlert: "BELUM BAYAR",
    deleteCustomer: "Hapus Pelanggan",
    deleteCustomerConfirm: "Hapus pelanggan ini? Semua kartu dan transaksi mereka akan dihapus selamanya.",
    waVipMsg: "Terima kasih telah membeli di Pizza 'N Gooo! Anda hemat uang dengan Kartu VIP hari ini! 🍕🔥",
    waFidelityMsg: "Terima kasih telah membeli di Pizza 'N Gooo! Poin Anda sekarang",
    pointsMsg: "poin. Kumpulkan terus untuk Pizza Gratis! 🍕🔥",
    selectStaff: "Pilih Staf",
    camera: "Kamera",
    // New Translations
    upcomingBirthdays: "🎂 Ulang Tahun (7 Hari)",
    topStaff: "🏆 Staf Terbaik (Pendaftaran)",
    weeklySales: "📉 Penjualan Mingguan",
    dormantCustomers: "💤 Pelanggan Tidur (>30 Hari)",
    sendWishes: "Kirim Ucapan",
    missYouMsg: "Kami merindukanmu di Pizza 'N Gooo! Datanglah kembali untuk hadiah spesial! 🍕",
    birthdayMsg: "Selamat Ulang Tahun dari Pizza 'N Gooo! 🎂 Rayakan bersama kami dan dapatkan hadiah spesial!",
    createVoucher: "Buat Voucher",
    voucherTitle: "Judul Voucher",
    voucherAmount: "Diskon/Nilai",
    voucherDesc: "Deskripsi",
    generateVoucher: "Buat & Bagikan",
    preview: "Pratinjau",
    marketingTools: "Alat Pemasaran",
    noBirthdays: "Tidak ada ulang tahun minggu ini.",
    noDormant: "Tidak ada pelanggan tidur.",
    totalSales: "Total Penjualan",
    last7Days: "7 Hari Terakhir"
  }
};
